### ISSUE TITLE
Err ProvisioningError(ServiceError(UnhandledResponseCode { http_code: 409 }))

### ISSUE THREAD

**Issue by jspricke** [hoehermann/purple-presage#5]
Tried with the latest master (ce26e54) I get the above error both with bitlbee and pidgin. Tried with my normal Signal account as well as a fresh one. Any hints?

**Comment by hoehermann** [comment]
Thank you for the report. This is the same as #4 and #2. I do am not sure why this happens, yet. Since the issues arise when using bitlbee, my guess is that bitlbee notices the connection is not set-up yet, then retries to link too quickly until it gets banned. I am far from sure, though.

**Comment by jspricke** [comment]
Thanks for your message. I understood #2 is solved in master or am I missing something? Also I also tried in pidgin and got the same error and got it from the start with a new phone number.

**Comment by hoehermann** [comment]
Then unfortunately, my answer is the same as on #4: It works for me and I have no idea why it does not work for you. 🙁

No, wait… it happens to other projects, too:
https://gitlab.com/schmiddi-on-mobile/flare/-/issues/221
https://gitlab.com/schmiddi-on-mobile/flare/-/issues/215

Allegedly, the problem is alleviated https://github.com/whisperfish/presage/commit/464626a. I updated purple-presage's current master branch to use that commit. Does it work for you?

**Comment by jspricke** [comment]
That was it, thanks!
